name: cyclic_dependency_checks
description: Cyclic Dependency checks for dart projects
version: 0.6.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  test: ^1.24.5
dependencies:
  args: ^2.4.2
