name: cyclic_dependency_checks
description: Cyclic Dependency checks for dart projects
version: 0.7.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  melos: ^6.1.0
  path: ^1.9.0
  test: ^1.24.5
dependencies:
  args: ^2.4.2
